### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by AlfreDGR** [BenCodez/MCPerks#24]
Is there an option and if there is not (to be able to add) that the perks work only for the user instead of the ALL SERVER?

**Comment by Ben12345rocks** [comment]
Already exists

**Comment by AlfreDGR** [comment]
Wich command is?

**Comment by Ben12345rocks** [comment]
Its a config option

**Comment by AlfreDGR** [comment]
There is permissions for each perk? Because i want perks for each rank

**Comment by Ben12345rocks** [comment]
There is. Look on the plugin page.

**Comment by AlfreDGR** [comment]
I put effect of perks only for one person but IncreaseMobDrops its for all. I dont know why?

**Comment by Ben12345rocks** [comment]
What do you mean by that? Send what you have?

**Comment by AlfreDGR** [comment]
In my server I want the effects of the benefits to be individual, I put in the configuration that each effect is per "player". I have been testing and it works but for example increasing mobs drops can be done by everyone

**Comment by Ben12345rocks** [comment]
I guess those are hard coded that way. Because when an entity dies it is too hard to figure out which player killed it.
